"""empty message

Revision ID: 5a0c46163cee
Revises: 02cf7d11ded7
Create Date: 2025-10-29 07:25:12.077820

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a0c46163cee"
down_revision: Union[str, Sequence[str], None] = "02cf7d11ded7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms_facilities", sa.Column("facility_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        op.f("rooms_facilities_facilities_id_fkey"),
        "rooms_facilities",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "rooms_facilities", "facilities", ["facility_id"], ["id"]
    )
    op.drop_column("rooms_facilities", "facilities_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms_facilities",
        sa.Column("facilities_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "rooms_facilities", type_="foreignkey")
    op.create_foreign_key(
        op.f("rooms_facilities_facilities_id_fkey"),
        "rooms_facilities",
        "facilities",
        ["facilities_id"],
        ["id"],
    )
    op.drop_column("rooms_facilities", "facility_id")
    # ### end Alembic commands ###
