"""empty message

Revision ID: 8a98dcce8e48
Revises: 18ab73336457
Create Date: 2025-10-20 12:56:29.287105

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a98dcce8e48"
down_revision: Union[str, Sequence[str], None] = "18ab73336457"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("room_id", sa.Integer(), nullable=False))
    op.drop_constraint(op.f("bookings_hotel_id_fkey"), "bookings", type_="foreignkey")
    op.create_foreign_key(None, "bookings", "rooms", ["room_id"], ["id"])
    op.drop_column("bookings", "hotel_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column("hotel_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "bookings", type_="foreignkey")
    op.create_foreign_key(
        op.f("bookings_hotel_id_fkey"), "bookings", "hotels", ["hotel_id"], ["id"]
    )
    op.drop_column("bookings", "room_id")
    # ### end Alembic commands ###
